# Gunakan image PHP 8.1 dengan FPM
FROM php:8.1-fpm

# Install sistem dependencies & PHP extensions yang diperlukan
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libonig-dev \
    libpq-dev \
    libxml2-dev \
    zip \
    curl \
    && docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath xml

# Install Composer (pakai versi terbaru)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory di dalam container
WORKDIR /var/www/html

# Copy semua file project ke dalam container
COPY . .

# Install dependency composer tanpa dev
RUN composer install --no-dev --optimize-autoloader

# Generate app key
# RUN php artisan key:generate

# Set permission storage dan bootstrap/cache (optional tapi direkomendasikan)
RUN chown -R www-data:www-data storage bootstrap/cache

# Expose port 8000 untuk Laravel serve
EXPOSE $PORT

# Jalankan Laravel server pada port 8000
CMD php artisan serve --host=0.0.0.0 --port=$PORT
